.Call <- base::.Call
.convolve2 <- NULL
.data_r2rust <- NULL
.state_r2rust <- NULL
.hyperparameters_r2rust <- NULL
.fit <- NULL
.log_likelihood_contributions <- NULL
.log_likelihood_contributions_of_missing <- NULL
.state_rust2r_as_reference <- NULL
.rust_free <- NULL
.all <- NULL
.fit_all <- NULL
.myrnorm <- NULL
.sample_multivariate_normal <- NULL
.zero <- NULL
